<?php

namespace App\Services\ConfigGenerator;

use App\Models\WebApp;

class PhpFpmConfigGenerator
{
    protected const DEFAULT_SETTINGS = [
        // Process Manager Settings
        'pm' => 'dynamic',
        'pm_max_children' => 5,
        'pm_start_servers' => 2,
        'pm_min_spare_servers' => 1,
        'pm_max_spare_servers' => 3,
        'pm_max_requests' => 500,
        'pm_process_idle_timeout' => '10s',

        // PHP Settings
        'upload_max_filesize' => '64M',
        'post_max_size' => '64M',
        'memory_limit' => '256M',
        'max_execution_time' => 30,
        'max_input_time' => 60,
        'max_input_vars' => 3000,
        'display_errors' => 'Off',
        'log_errors' => 'On',
        'error_reporting' => 'E_ALL & ~E_DEPRECATED & ~E_STRICT',

        // Security Settings
        'open_basedir' => null, // Will be set dynamically
        'disable_functions' => 'exec,passthru,shell_exec,system,proc_open,popen,parse_ini_file,show_source',
        'allow_url_fopen' => 'On',
        'allow_url_include' => 'Off',
        'expose_php' => 'Off',

        // Session Settings
        'session.gc_maxlifetime' => 1440,
        'session.cookie_httponly' => 'On',
        'session.cookie_secure' => 'On',

        // OPcache (enabled by default)
        'opcache.enable' => 1,
        'opcache.memory_consumption' => 128,
        'opcache.max_accelerated_files' => 10000,
        'opcache.validate_timestamps' => 0,
    ];

    public function generate(WebApp $app, array $customSettings = []): string
    {
        $settings = array_merge(self::DEFAULT_SETTINGS, $app->settings ?? [], $customSettings);
        $systemUser = $app->system_user;
        $phpVersion = $app->php_version;
        $appId = $app->id;
        $rootPath = $app->root_path;
        $domain = $app->domain;

        // Set open_basedir dynamically
        if ($settings['open_basedir'] === null) {
            $settings['open_basedir'] = "{$rootPath}:/tmp:/usr/share/php";
        }

        // Calculate pool settings based on server resources if available
        $poolSettings = $this->calculatePoolSettings($app, $settings);

        // Build PHP settings section
        $phpSettings = $this->buildPhpSettings($settings);

        // Build environment variables if any
        $envVars = $this->buildEnvironmentVars($app);

        return <<<FPM
; PHP-FPM Pool Configuration
; App: {$domain}
; Generated by SiteKit

[{$appId}]
; Process Ownership
user = {$systemUser}
group = {$systemUser}

; Socket Configuration
listen = /var/run/php/php{$phpVersion}-fpm-{$appId}.sock
listen.owner = www-data
listen.group = www-data
listen.mode = 0660

; Process Manager
pm = {$poolSettings['pm']}
pm.max_children = {$poolSettings['max_children']}
pm.start_servers = {$poolSettings['start_servers']}
pm.min_spare_servers = {$poolSettings['min_spare_servers']}
pm.max_spare_servers = {$poolSettings['max_spare_servers']}
pm.max_requests = {$poolSettings['max_requests']}
pm.process_idle_timeout = {$poolSettings['process_idle_timeout']}

; Process Status (for monitoring)
pm.status_path = /fpm-status-{$appId}
ping.path = /fpm-ping-{$appId}
ping.response = pong

; Working Directory
chdir = {$rootPath}

; Request Handling
request_terminate_timeout = {$settings['max_execution_time']}s
request_slowlog_timeout = 5s
slowlog = /var/log/php{$phpVersion}-fpm/{$appId}.slow.log

; Error Logging
catch_workers_output = yes
decorate_workers_output = no
php_admin_flag[log_errors] = On
php_admin_value[error_log] = /var/log/php{$phpVersion}-fpm/{$appId}.error.log

{$phpSettings}
{$envVars}
FPM;
    }

    public function generateForQueue(WebApp $app): string
    {
        $systemUser = $app->system_user;
        $phpVersion = $app->php_version;
        $appId = $app->id;
        $rootPath = $app->root_path;

        // Queue workers need more relaxed settings
        return <<<FPM
; PHP-FPM Pool for Queue Workers
; App: {$app->domain}

[{$appId}-queue]
user = {$systemUser}
group = {$systemUser}

listen = /var/run/php/php{$phpVersion}-fpm-{$appId}-queue.sock
listen.owner = www-data
listen.group = www-data
listen.mode = 0660

pm = ondemand
pm.max_children = 2
pm.process_idle_timeout = 60s
pm.max_requests = 100

chdir = {$rootPath}

; Relaxed settings for long-running queue jobs
php_admin_value[max_execution_time] = 0
php_admin_value[memory_limit] = 512M
php_admin_value[max_input_time] = -1

; Disable exec restrictions for queue workers
php_admin_value[disable_functions] = ""
FPM;
    }

    protected function calculatePoolSettings(WebApp $app, array $settings): array
    {
        $server = $app->server;
        $memoryMb = $server?->memory_mb ?? 1024;
        $cpuCount = $server?->cpu_count ?? 1;

        // Default pool settings
        $pool = [
            'pm' => $settings['pm'] ?? 'dynamic',
            'max_children' => $settings['pm_max_children'] ?? 5,
            'start_servers' => $settings['pm_start_servers'] ?? 2,
            'min_spare_servers' => $settings['pm_min_spare_servers'] ?? 1,
            'max_spare_servers' => $settings['pm_max_spare_servers'] ?? 3,
            'max_requests' => $settings['pm_max_requests'] ?? 500,
            'process_idle_timeout' => $settings['pm_process_idle_timeout'] ?? '10s',
        ];

        // Auto-calculate if server info is available
        if ($server && $memoryMb > 0) {
            // Estimate ~50MB per PHP worker
            $workerMemory = 50;
            // Reserve 30% for system and other services
            $availableForPhp = $memoryMb * 0.3;
            // Count all webapps on this server
            $appCount = max(1, $server->webApps()->count());

            // Calculate max children per app
            $maxPerApp = max(2, floor($availableForPhp / $workerMemory / $appCount));
            $pool['max_children'] = min($maxPerApp, 50); // Cap at 50

            // Derive other values
            $pool['start_servers'] = max(1, floor($pool['max_children'] / 4));
            $pool['min_spare_servers'] = max(1, floor($pool['max_children'] / 4));
            $pool['max_spare_servers'] = max(2, floor($pool['max_children'] / 2));
        }

        return $pool;
    }

    protected function buildPhpSettings(array $settings): string
    {
        $phpSettings = [
            'upload_max_filesize',
            'post_max_size',
            'memory_limit',
            'max_execution_time',
            'max_input_time',
            'max_input_vars',
            'display_errors',
            'error_reporting',
            'open_basedir',
            'allow_url_fopen',
            'allow_url_include',
            'expose_php',
            'session.gc_maxlifetime',
            'session.cookie_httponly',
            'session.cookie_secure',
            'opcache.enable',
            'opcache.memory_consumption',
            'opcache.max_accelerated_files',
            'opcache.validate_timestamps',
        ];

        $output = "\n; PHP Configuration\n";

        foreach ($phpSettings as $key) {
            if (isset($settings[$key])) {
                $value = $settings[$key];
                if (is_bool($value)) {
                    $value = $value ? 'On' : 'Off';
                }
                $output .= "php_admin_value[{$key}] = {$value}\n";
            }
        }

        // Security settings (admin flags that cannot be overridden)
        if (isset($settings['disable_functions']) && !empty($settings['disable_functions'])) {
            $output .= "php_admin_value[disable_functions] = {$settings['disable_functions']}\n";
        }

        return $output;
    }

    protected function buildEnvironmentVars(WebApp $app): string
    {
        $envVars = $app->environment_variables;
        if (empty($envVars)) {
            return '';
        }

        if (is_string($envVars)) {
            $envVars = json_decode($envVars, true) ?? [];
        }

        if (empty($envVars)) {
            return '';
        }

        $output = "\n; Environment Variables\n";
        foreach ($envVars as $key => $value) {
            // Sanitize value for FPM config
            $value = str_replace('"', '\\"', $value);
            $output .= "env[{$key}] = \"{$value}\"\n";
        }

        return $output;
    }

    /**
     * Get available PHP versions for the system
     */
    public static function availableVersions(): array
    {
        return ['8.5', '8.4', '8.3', '8.2', '8.1'];
    }

    /**
     * Get recommended settings based on app type
     */
    public static function getPresetSettings(string $appType): array
    {
        return match ($appType) {
            'laravel' => [
                'memory_limit' => '256M',
                'max_execution_time' => 60,
                'upload_max_filesize' => '64M',
                'post_max_size' => '64M',
                'opcache.validate_timestamps' => 0,
            ],
            'wordpress' => [
                'memory_limit' => '256M',
                'max_execution_time' => 300,
                'upload_max_filesize' => '128M',
                'post_max_size' => '128M',
                'opcache.validate_timestamps' => 1,
            ],
            'magento' => [
                'memory_limit' => '768M',
                'max_execution_time' => 600,
                'upload_max_filesize' => '64M',
                'post_max_size' => '64M',
                'opcache.memory_consumption' => 512,
            ],
            default => [],
        };
    }
}
